update md2ansi 0.4.20(2)

diff --git a/md2ansi b/md2ansi
--- a/md2ansi
+++ b/md2ansi
@@ -1,6 +1,12 @@
 #!/bin/bash
 #shellcheck disable=SC2034
-set -e
+# Script  : $PRG vs $VERSION
+# Desc    : Print formatted ANSI output to terminal from Markdown file.md.
+# Synopsis: $PRG [file.md [...]] [< md_input_stream]
+# Examples: $PRG < README.md
+#         : $PRG < *.md
+#         : $PRG file1.md
+#         : $PRG file1.md file2.md file3.md <file4.md
 
 md2ansi() {
   # try to inherit current global COLUMNS
@@ -201,6 +207,19 @@ transform_line() {
   echo -ne "$new_line"
 }
 
+# bash_docstring.lite
+usage() {
+  [[ $0 == 'bash' ]] && return 0
+  while IFS= read -r line; do
+    line=${line#"${line%%[![:space:]]*}"}
+    [[ -z "$line" ]] && continue
+    [[ ${line:0:1} == '#' ]] || break
+    [[ $line == '#' ]] && { echo; continue; }
+    [[ ${line:0:2} == '# '  || ${line:0:2} == '#@' ]] && eval "echo \"${line:2}\""
+  done <"$0"
+  return 0
+}
+
 center_text() {
   local -i w=$1; shift
   local -- text
@@ -240,41 +259,30 @@ trim() {
 }
 declare -fx trim
 
-if [[ "${BASH_SOURCE[0]}" == "${0}" ]]; then #=====================================
-declare -- _ent_0=$(readlink -fn -- "$0") || _ent_0=''
-declare -- PRG=${_ent_0##*/}
-declare -- PRGDIR=${_ent_0%/*}
-declare -- version='0.4.20'
-_main() {
-  usage() {
-  cat <<EOT
-Script  : $PRG vs $version
-Desc    : Print formatted ANSI output to terminal from Markdown file.md.
-Synopsis: $PRG [file.md [...]] [< md_input_stream]
-Examples: $PRG < README.md
-        : $PRG < *.md
-        : $PRG file1.md
-        : $PRG file1.md file2.md file3.md <file4.md
-EOT
-  }
-  local -a args=()
+if [[ "${BASH_SOURCE[0]}" == "$0" ]]; then #=====================================
+  set -euo pipefail
+  declare -- PRG0
+  PRG0=$(readlink -fn -- "$0")
+  declare -- PRG=${PRG0##*/}
+  declare -- PRGDIR=${PRG0%/*}
+  declare -- VERSION='0.4.20(2)'
+
+  declare -a args=()
   while(($#)); do case "$1" in
-    -V|--version) echo "$PRG $version"; return 0 ;;
-    -h|--help)    usage; return 0 ;;
-    -?|--*)       >&2 echo "$PRG: Invalid option '$1'"; exit 22 ;;
+    -V|--version) echo "$PRG $VERSION"; exit 0 ;;
+    -h|--help)    usage; exit 0 ;;
+    -?|--*)       >&2 echo "$PRG: error: Invalid option '$1'"; exit 22 ;;
     *)            args+=( "$1" ) ;;
   esac; shift; done
   if ((${#args[@]})); then
-    local -- mdfile md=''
+    declare -- mdfile md=''
     for mdfile in "${args[@]}"; do
-      [[ -f "$mdfile" ]] || { >&2 echo "$PRG: File '$mdfile' not found"; exit 1 ; }
+      [[ -f "$mdfile" ]] || { >&2 echo "$PRG: error: File '$mdfile' not found"; exit 1 ; }
       md+=$(cat -s -- "$mdfile"; echo)
     done
     md2ansi <<<"$md"
   fi
   [[ ! -t 0 ]] && md2ansi
-}
-
-_main "$@"
 fi
+
 #fin
